config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  get "search" => "searches#search_result"
  resources :movies do
    resources :movie_comments, only: [:create, :destroy, :index]
     resource :favorites, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :movie_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :movie_image, content_type: ["image/jpg", "image/png", "image/gif", "image/jpeg"]

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :movie_image, presence: true
  validates :body, presence: true
  # validates :star, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @movie = Movie.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @movie= Movie.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @movie = Movie.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @movie = Movie.where("title LIKE?","%#{word}%")
    else
      @movie = Movie.all
    end
  end

end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  validates :movie_name, length: {maximum: 50}

  has_many :movies, dependent: :destroy
  has_many :movie_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image, content_type: ["image/jpg", "image/png", "image/gif", "image/jpeg"]

  # class Follower フォロ-する側目線
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :follower_relationships, source: :followed

  # class Followed フォロ-される側目線
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :followed_relationships, source: :follower

    # model/user.rb
  # ユーザーをフォローする
  def follow(user_id)
   follower_relationships.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
   follower_relationships.find_by(followed_id: user_id).destroy
  end
  # フォロー確認をおこなう
  def following?(user)
   self.followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    movie = Movie.find(params[:movie_id])
    favorite = current_user.favorites.new(movie_id: movie.id)
    favorite.save
    redirect_to movies_path
  end

  def destroy
    movie = Movie.find(params[:movie_id])
    favorite = current_user.favorites.find_by(movie_id: movie.id)
    favorite.destroy
    redirect_to movies_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/movie_comments_controller.rb
class MovieCommentsController < ApplicationController
  def create
    movie = Movie.find(params[:movie_id])
    comment = current_user.movie_comments.new(movie_comment_params)
    comment.movie_id = movie.id
    if comment.save
      redirect_to movie_movie_comments_path(movie_id: movie.id)
    else
      render movies_path
    end
  end

  def destroy
    comment = MovieComment.find_by(id: params[:id], movie_id: params[:movie_id])
    if comment.destroy
      redirect_to movie_movie_comments_path(movie_id: params[:movie_id])
    else
      render movies_path
    end
  end

  def index
    @movie = Movie.find(params[:movie_id])
    @movie_comment = MovieComment.new
  end

  private

  def movie_comment_params
    params.require(:movie_comment).permit(:comment)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  def index
    @movies = Movie.all.order(created_at: :desc)
  end

  def show
    @movie = Movie.find(params[:id])
    @movie_comment = MovieComment.new
    @user = @movie.user
  end

  def new
    @movie = Movie.new
  end

  def edit
     @movie = Movie.find(params[:id])
    unless @movie.user.id == current_user.id
      redirect_to movies_path
    end
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    if @movie.save
      flash[:notice] = "You have created movie successfully."
      redirect_to movies_path
    else
      render :new
    end

  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      flash[:notice] = "You have updated movie successfully."
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :body, :movie_image, :star)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @followers = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search_result
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @movies = Movie.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @movies = @user.movies
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def create
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :movie_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movie_comments_helper.rb
module MovieCommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="background">
  <div class="row">
    <h1 class="px-3 mx-auto">ようこそ<i class="fas fa-book"></i><strong>Moviegoer</strong>へ!</h1>
    <p>ここは映画との思い出をより深く、大切に、記録する場所です。</p>
    <p>映画の思い出をたくさん記録して、映画好きな友達も増やしていきましょう。</p>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1><strong>Moviegoer</strong>へようこそ!!</h1>
      <p><strong>Moviegoer</strong>で </p>
      <p>映画との思い出を投稿していこう。</p>
      <p> 映画好きのともだちを作って、映画への愛を深めよう！</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movie_comments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <div class="new-comment card-text">
        <%= form_with(model:[@movie, @movie_comment]) do |f| %>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">コメントする</label>
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
          </div>
          <%= f.submit "Send", class:"btn btn-md btn-info mt-1 float-right" %>
        <% end %>
      </div>
       <div class="row">
        <div class="comments card-text">
        <hr>
        <hr>
        <h4 class="mt-1"><%= @movie.movie_comments.count %>件コメント</h4>
        <% @movie.movie_comments.each do |movie_comment| %>
          <div class="media border mb-3">
            <%= attachment_image_tag movie_comment.user, :profile_image, :fill, 40, 40, fallback: "no-image.jpg", class: "rounded-circle m-1" %>
            <div class="media-body mb-3">
              <p><%= movie_comment.created_at.strftime('%Y/%m/%d')%></p>
              <p><%= movie_comment.comment %></p>
              <% if movie_comment.user == current_user %>
                <%= link_to "Delete", movie_movie_comment_path(movie_comment.movie, movie_comment), method: :delete, class: "btn btn-sm btn-danger pull-right" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movies/_moviepost.html.erb
<div class="card-list-container py-5">
  <% movies.each do |movie| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to movie_path(movie.id) do %>
      <%= attachment_image_tag movie, :movie_image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
       <p class="card-title">
        <%= attachment_image_tag movie.user, :profile_image, :fill, 45, 45, fallback: "no-image.jpg", class:"rounded-circle"; %>
        <%= link_to(user_path(movie.user.id), class:"text-dark") do %>
          <span>
            <font size="5"><strong><%= movie.user.name %></strong></font>
          </span>
          <% end %>

          <div class="inbox">
          <span class="flex-right"><i class="fa fa-comment"></i> <%= link_to "#{movie.movie_comments.count}", movie_movie_comments_path(movie_id: movie.id), class:"text-dark" %> ｜ </span>

          <% if movie.favorited_by?(current_user) %>
          <span class="flex-right">
            <%= link_to(movie_favorites_path(movie), class:"text-dark", method: :delete) do %>
              <i class="fas fa-heart" aria-hidden="true"></i> <%= movie.favorites.count %>
            <% end %>
          </span>
          <% else %>
          <span>
            <%= link_to(movie_favorites_path(movie), class:"text-dark" "text-right", method: :post) do %>
              <i class="far fa-heart" aria-hidden="true"></i> <%= movie.favorites.count %>
            <% end %>
          </span>
        <% end %>
        </div>

        </p>

        <div class="col-10">
          <p class="card-title">
            <%= link_to(movie_path(movie.id), class:"text-dark") do %>
              <strong><i class="far fa-file-video"></i><span> <%= movie.title %></span></strong>
            <% end %>
          </p>
          <div class="star_<%= movie.id %>"></div>
          <p class="card-text">Note：<%= movie.body %></p>
          <span><%= link_to "#{movie.movie_comments.count} Comment", movie_path(movie.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
 </div>

  <script>
    $('.star_<%= movie.id %>').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    score: <%= movie.star %>,
    readOnly: true,
    half: true
    });
  </script>
<% end %>

app/views/movies/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form middle">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Movie']]) %>
      <%= f.select :search, options_for_select([["perfect","perfect_match"], ["forward","forward_match"],  ["backword","backword_match"], ["partical","partial_match"]]) %>
      <%= f.submit "Search", class: "btn-sm btn-info" %>
    <% end %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="container">
  <% if @movie.errors.any? %>
    <%= @movie.errors.count %>件のエラーが発生しました
    <ul>
      <% @movie.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Edit post</h2>
      <%= form_with model: @movie, local:true do |f| %>

      <div class="form-group">
        <label for="movie_image">Photo</label>
        <%= f.attachment_field :movie_image, class: "form-control-file movie_image" %>
      </div>

      <div class="form-group">
        <label for="title">Title</label>
        <%= f.text_field :title, class: "form-control title" %>
      </div>

      <div class="form-group">
        <label for="body">Note</label>
        <%= f.text_area :body, class: "form-control body" %>
      </div>

      <div class="field" id="star">
        <label for="star">Star</label>
      </div>

      <div class="form-group">
        <h4><%= f.submit 'Update Post', class: "btn btn-secondary" %></h4>
      </div>
      <% end %>
      <%= link_to "Show", movie_path(@movie) %>
      <%= link_to "Back", movies_path %>
    </div>
  </div>
</div>

<script>
$('#star').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'movie[star]',
  half: true
});
</script>

app/views/movies/index.html.erb
<%= render 'moviepost', movies: @movies, movie: @movie %>

app/views/movies/new.html.erb
<div class="container">
  <% if @movie.errors.any? %>
    <%= @movie.errors.count %>件のエラーが発生しました
    <ul>
      <% @movie.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>New post</h2>
      <%= form_with model: @movie, local:true do |f| %>

      <div class="form-group">
        <label for="movie_image">Photo</label>
        <%= f.attachment_field :movie_image, class: "form-control-file movie_image" %>
      </div>

      <div class="form-group">
        <label for="title">Title</label>
        <%= f.text_field :title, class: "form-control title" %>
      </div>

      <div class="form-group">
        <label for="body">Note</label>
        <%= f.text_area :body, class: "form-control body" %>
      </div>

      <div class="field" id="star">
        <label for="star">Star</label>
      </div>

      <div class="form-group">
        <h4><%= f.submit 'Post', class: "btn btn-secondary" %></h4>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
$('#star').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'movie[star]',
  half: true
});
</script>

app/views/movies/show.html.erb
<div class="post-detail py-5 bg-light">
  <div class="card w-75 mx-auto mt-4 shadow-lg">
    <%= attachment_image_tag @movie, :movie_image, class:"card-img-top"; %>
    <div class="card-body">
      <div class="row">
        <div class="col-10">
          <p class="card-title">
            <%= attachment_image_tag @movie.user, :profile_image, :fill, 45, 45, fallback: "no-image.jpg", class:"rounded-circle" %>
            <%= link_to(user_path(@user.id), class:"text-dark") do %>
            <span>
              <font size="5"><strong><%= @movie.user.name %></strong></font>
            </span>
            <% end %>
          </p>
          <p class="card-title">
            <%= link_to(movie_path(@movie.id), class:"text-dark") do %>
              <strong><i class="far fa-file-video"></i><span> <%= @movie.title %></span></strong>
            <% end %>
          </p>
          <p class="card-title">Note：<%= @movie.body %></p>
          <span><i class="fas fa-user"></i> By <%= @movie.user.name %> ｜ </span>
          <span><i class="fa fa-calendar"></i> <%= @movie.created_at.strftime('%Y/%m/%d') %> ｜ </span>
          <span><i class="fa fa-comment"></i> <%= link_to "#{@movie.movie_comments.count}", movie_movie_comments_path(movie_id: @movie.id), class:"text-dark" %> ｜ </span>
          <% if @movie.favorited_by?(current_user) %>
            <span>
              <%= link_to(movie_favorites_path(@movie), class:"text-dark", method: :delete) do %>
                <i class="fas fa-heart" aria-hidden="true"></i> <%= @movie.favorites.count %>
              <% end %>
            </span>
            <% else %>
            <span>
              <%= link_to(movie_favorites_path(@movie), class:"text-dark", method: :post) do %>
                <i class="far fa-heart" aria-hidden="true"></i> <%= @movie.favorites.count %>
              <% end %>
            </span>
          <% end %>
          <% if @movie.user == current_user %>
            <span> ｜ </span><%= link_to "Delete", movie_path(@movie), class:"btn btn-sm btn-danger", method: :delete, data: {confirm: "本当に消しますか？"} %>
            <span> ｜ </span><%= link_to "Edit", edit_movie_path(@movie.id), class: "btn btn-sm btn-success" %></td>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<table class="table table-hover table-inverse">
<% if @followers.exists? %>
  <thead>
    <tr>
      <th>Name</th>
      <th>Follow</th>
      <th>Follower</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @followers.each do |follower| %>
      <tr>
        <td>
          <%= attachment_image_tag follower, :profile_image, :fill, 40, 40, fallback: "no-icon.jpg", class:"my-1 rounded-circle" %>
          <span><strong><%= follower.name %></strong></span>
        </td>
        <td><%= follower.followings.count %></td>
        <td><%= follower.followers.count %></td>
        <td><%= link_to "Show", user_path(follower), class: "btn btn-info pull-right" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>No users</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Following Users</h2>
<table class="table table-hover table-inverse">
<% if @users.exists? %>
  <thead>
    <tr>
      <th>Name</th>
      <th>Follow</th>
      <th>Follower</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg", class:"my-1 rounded-circle" %>
          <span><strong><%= user.name %></strong></span>
        </td>
        <td><%= user.followings.count %></td>
        <td><%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user), class: "btn btn-info pull-right" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>No users</p>
<% end %>

app/views/searches/search_result.html.erb
<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
  <h2>User search for <%= @word %> </h2>
   <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Follow</th>
      <th>Follower</th>
      <th colspan="3"></th>
    </tr>
   </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
    	 <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpg", class:"my-1 rounded-circle" %></td>
       <td><strong><%= user.name %></strong></td>
       <td><%= link_to "#{user.followings.count}", user_followings_path(user.id) %></td>
       <td><%= link_to "#{user.followers.count}", user_followers_path(user.id) %></td>
       <td><% if current_user.id != user.id %>
             <% if current_user.following?(user) %>
             <th><%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %></th>
              <% else %>
             <th><%= link_to "Follow", user_relationships_path(user.id), method: :post %></th>
             <% end %>
          <% end %>
       </td>
       <td><%= link_to "Show", user_path(user), class: "btn btn-info pull-right" %></td>
      </tr>
      <% end %>
    </tbody>
  <% else %>
  <h2>Movie search for <%= @word %> </h2>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Note</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td>
    		      <%= link_to user_path(movie.user) do %>
    		      <span><%= attachment_image_tag movie.user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg", class:"m-2 rounded-circle" %></span>
    		      <% end %>
    		      <span><strong><%= movie.user.name %></strong></span>
    		  </td>
          <td><%=link_to movie.title, movie_path(movie) %></td>
          <td><%= movie.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/_userinfo.html.erb
<div class="col-md-3 sticky">
  <div class="text-left">
    <h2>User info</h2>
  </div>
    <div class="text-center">
    <%= attachment_image_tag user, :profile_image, :fill, 150, 150, fallback: "no-image.jpg", class:"my-3 rounded-circle" %>
    </div>
    <table class="table">
      <tbody><tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>your movie</th>
        <th><%= user.movie_name %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
      </tr>
      <tr>
        <% if current_user.id != user.id %>
          <% if current_user.following?(user) %>
            <th><%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %></th>
          <% else %>
            <th><%= link_to "Follow", user_relationships_path(user.id), method: :post %></th>
          <% end %>
        <% end %>
      </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to '', edit_user_path(user), class: "btn btn-outline-secondary btn-Primary fas fa-cogs" %>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="container">

  <% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
  　<li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>

      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class: "form-control name" %>
      </div>

      <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>

      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>

      <div class="form-group">
        <label for="user_movie_name">your movie</label>
        <%= f.text_field :movie_name, class: "form-control movie_name" %>
      </div>

      <div class="form-group">
        <h4><%= f.submit 'Update User', class: "btn btn-secondary" %></h4>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/userinfo', user: @user %>

    <div class="col-md-8 offset-md-1">
  		<h2>Users</h2>
  		<table class="table table-hover table-inverse">
  		  <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
    		 <% @users.each do |user| %>
    		  <tr>
    		    <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpg", class:"mt-1 rounded-circle" %></td>
      			<td><strong><%= user.name %></strong></td>
      			<td><%= user.introduction %></td>
        		<td><% if current_user.id != user.id %>
                  <% if current_user.following?(user) %>
                    <th><%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %></th>
                  <% else %>
                    <th><%= link_to "Follow", user_relationships_path(user.id), method: :post %></th>
                  <% end %>
                <% end %></td>

      			<td><%= link_to "Show", user_path(user), class: "btn btn-info pull-right" %></td>
      		</tr>
      		<% end %>
      	</tbody>
  		</table>
  	</div>
  </div>
</div>